
name: firesdk-api

image: emmachang00000/firesdk-api


service:
  - name: firesdk-api
    httpTargetPort: 12345

ingressroute:
  - certResolver: cf
    name: firesdk-api
    domain: firesdk-api.emmatest.online
    service: firesdk-api

mountSecret:
- name: fcm-service
  readOnly: true
  mountPath: /app/fcm-service-account.json
  